version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: zip
          command: |
            echo zipping
            cd extension
            zip -r /tmp/extension.zip *
            cd ..
      - store_artifacts:
          path: /tmp/extension.zip
          destination: extension.zip
